name: Sync to Deployment Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to Deployment Repo
        run: |
          git remote add deployment https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/jinyang628/vercel-whale-platform.git
          git push deployment main:main --force
        env:
          PAT_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}