name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Deployment Repo
        uses: actions/checkout@v2
        with:
          repository: jinyang628/vercel-whale-platform
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Pull from Working Repo
        run: |
          git remote add working-repo https://github.com/huge-whale/whale-platform.git
          git fetch working-repo
          git merge working-repo/main --allow-unrelated-histories
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}